architect:
  - amihaiemil
docker:
  as_root: true
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
install: |-
  chmod +x ./install_phantomjs.sh
  ./install_phantomjs.sh
merge:
  script: |-
    mvn clean install -Pitcases
deploy:
  script:
   - echo "Any deployment script here..."
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -e
    git commit -am "${tag}"
    mvn clean deploy --settings ../settings.xml
