architect:
  - amihaiemil
docker:
  as_root: true
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
install: |-
  chmod +x ./install_phantomjs.sh
  sudo ./install_phantomjs.sh
merge:
  script: |-
    mvn clean install -Pitcases
deploy:
  script:
   - echo "Any deployment script here..."
decrypt:
  settings.xml: "repo/sonatype/settings.xml.asc"
  pubring.gpg: "repo/sonatype/pubring.gpg.asc"
  secring.gpg: "repo/sonatype/secring.gpg.asc"
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}" -e
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings ../settings.xml
