language: java
jdk:
  # - oraclejdk7
  - openjdk7
sudo: required
dist: trusty
addons:
  chrome: stable
before-script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
script:
  - set -e
  - whereis google-chrome
  - google-chrome --version
  - whereis chromedriver
  - mvn clean install -Pitcases jacoco:report coveralls:report

