language: java
jdk:
  - oraclejdk7
  - openjdk7
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - nginx
      - realpath
      - google-chrome-stable
before-script:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
script:
  - set -e
  - phantomjs --version
  - whereis phantomjs
  - whereis google-chrome
  - google-chrome --version
  - whereis chromium-browser
  - whereis chromium-chromedriver
  - mvn clean install -Pitcases jacoco:report coveralls:report

