language: java
jdk:
  - oraclejdk7
  - openjdk7
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - nginx
      - realpath
      - google-chrome-stable
install: # Install ChromeDriver.
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before-script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
script:
  - set -e
  - whereis google-chrome
  - google-chrome --version
  - whereis chromium-browser
  - chromium-browser --version
  - whereis chromedriver
  - mvn clean install -Pitcases jacoco:report coveralls:report

