language: java
jdk:
  - oraclejdk7
  - openjdk7
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - nginx
      - realpath
      - google-chrome-stable
script:
  - set -e
  - phantomjs --version
  - whereis phantomjs
  - whereis google-chrome
  - google-chrome --version
  - mvn clean install -Pitcases jacoco:report coveralls:report

